### ISSUE TITLE
AttributeError: module 'torch.nn.functional' has no attribute 'interpolate'

### ISSUE THREAD

**Issue by upuil** [CSAILVision/semantic-segmentation-pytorch#135]
pu@bogon semantic-segmentation-pytorch]$ ./demo_test.sh
Input arguments:
test_imgs        ['ADE_val_00001519.jpg']
model_path       baseline-resnet50dilated-ppm_deepsup
suffix           _epoch_20.pth
arch_encoder     resnet50dilated
arch_decoder     ppm_deepsup
fc_dim           2048
num_val          -1
num_class        150
batch_size       1
imgSize          [300, 400, 500, 600]
imgMaxSize       1000
padding_constant 8
segm_downsampling_rate 8
result           ./
gpu_id           0
Loading weights for net_encoder
Loading weights for net_decoder
       # samples: 1
  0%|                                                     | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "test.py", line 181, in <module>
    main(args)
  File "test.py", line 112, in main
    test(segmentation_module, loader_test, args)
  File "test.py", line 62, in test
    pred_tmp = segmentation_module(feed_dict, segSize=segSize)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pu/semantic-segmentation-pytorch/models/models.py", line 46, in forward
    pred = self.decoder(self.encoder(feed_dict['img_data'], return_feature_maps=True), segSize=segSize)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pu/semantic-segmentation-pytorch/models/models.py", line 470, in forward
    ppm_out.append(nn.functional.interpolate(
  **AttributeError: module 'torch.nn.functional' has no attribute 'interpolate'**

**Comment by hangzhaomit** [comment]
@upuil Can you check Pytorch version?

**Comment by upuil** [comment]
@hangzhaomit The torch version is 0.4
