### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by loveis98** [CSAILVision/semantic-segmentation-pytorch#162]

**Comment by loveis98** [comment]
Now I try to train on ADE20K dataset, but I see the same error. 
```
Input arguments:
weight_decay     0.0001
random_flip      True
epoch_iters      5000
workers          16
seed             304
start_epoch      1
num_class        150
imgMaxSize       1000
fc_dim           2048
lr_encoder       0.02
arch_encoder     resnet50dilated
list_val         ./data/validation.odgt
weights_encoder  
lr_pow           0.9
deep_sup_scale   0.4
weights_decoder  
batch_size_per_gpu 2
ckpt             ./ckpt
imgSize          [300, 375, 450, 525, 600]
lr_decoder       0.02
segm_downsampling_rate 8
optim            SGD
list_train       ./data/train.odgt
id               baseline
fix_bn           False
root_dataset     ./data/
disp_iter        20
padding_constant 8
arch_decoder     ppm_deepsup
beta1            0.9
gpus             0-3
num_epoch        20
Model ID: baseline-resnet50dilated-ppm_deepsup-ngpus4-batchSize8-imgMaxSize1000-paddingConst8-segmDownsampleRate8-LR_encoder0.02-LR_decoder0.02-epoch20
# samples: 20210
1 Epoch = 5000 iters
Traceback (most recent call last):
  File "train.py", line 334, in <module>
    main(args)
  File "train.py", line 190, in main
    iterator_train = iter(loader_train)
  File "/home/ponomareva/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 419, in __iter__
    return DataLoaderIter(self)
  File "/home/ponomareva/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 244, in __init__
    self._put_indices()
  File "/home/ponomareva/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 292, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/ponomareva/semantic-segmentation-pytorch/lib/utils/data/sampler.py", line 119, in __iter__
    for idx in self.sampler:
  File "/home/ponomareva/semantic-segmentation-pytorch/lib/utils/data/sampler.py", line 50, in __iter__
    return iter(torch.randperm(len(self.data_source)).long())
RuntimeError: $ Torch: not enough memory: you tried to allocate 74GB. Buy new RAM! at /pytorch/aten/src/TH/THGeneral.cpp:204
```

**Comment by zhukaii** [comment]
I also encountered the same problem. Is there any solution?

**Comment by komms** [comment]
Training should be done on mutiple GPU's. Refer #41

**Comment by hangzhaomit** [comment]
@loveis98 
Our customized DataParallel only supports multi-gpu training. But in the upcoming version (```distributed``` branch), single-gpu training will be supported.

**Comment by adityashrm21** [comment]
You might want to try this:
https://github.com/CSAILVision/semantic-segmentation-pytorch/issues/203#issuecomment-562524601
