### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Chris0919** [CSAILVision/semantic-segmentation-pytorch#167]
`
Input arguments:
deep_sup_scale   0.4
imgSize          [300, 375, 450, 525, 600]
arch_decoder     ppm_deepsup
list_train       ./data/train.odgt
padding_constant 8
id               baseline
root_dataset     ./data/
epoch_iters      5000
lr_decoder       0.02
start_epoch      1
batch_size_per_gpu 2
arch_encoder     resnet50dilated
lr_encoder       0.02
weights_encoder  
workers          16
num_epoch        20
gpus             0
optim            SGD
ckpt             ./ckpt
weights_decoder  
lr_pow           0.9
random_flip      True
beta1            0.9
list_val         ./data/validation.odgt
weight_decay     0.0001
imgMaxSize       1000
segm_downsampling_rate 8
disp_iter        20
seed             304
fc_dim           2048
fix_bn           False
num_class        150
Model ID: baseline-resnet50dilated-ppm_deepsup-ngpus1-batchSize2-imgMaxSize1000-paddingConst8-segmDownsampleRate8-LR_encoder0.02-LR_decoder0.02-epoch20
# samples: 20210
1 Epoch = 5000 iters
Traceback (most recent call last):
  File "train.py", line 325, in <module>
    main(args)
  File "train.py", line 200, in main
    train(segmentation_module, iterator_train, optimizers, history, epoch, args)
  File "train.py", line 31, in train
    batch_data = next(iterator)
  File "/home/cc/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 283, in __next__
    return self._process_next_batch(batch)
  File "/home/cc/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 303, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/cc/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/cc/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/cc/semantic-segmentation-pytorch/dataset.py", line 144, in __getitem__
    assert(segm.ndim == 2)
AttributeError: 'NoneType' object has no attribute 'ndim'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cc/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 70, in _worker_manager_loop
    r = in_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 345, in get
    return ForkingPickler.loads(res)
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/reductions.py", line 256, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)

ConnectionResetError: [Errno 104] Connection reset by peer

`
Hi,does anyone have the same error like this?
I wonder whats causing the error, and how should the error be handled.
Is it caused by the sever or something else?

**Comment by komms** [comment]
how many GPUS are you using?

**Comment by hangzhaomit** [comment]
I think it is because of missing data. I will close this for now.
