### ISSUE TITLE
Encounter RuntimeError with cuda when trying to train the model.

### ISSUE THREAD

**Issue by caidwang** [CSAILVision/semantic-segmentation-pytorch#192]
I shared three GPUs with peers at now.  When trying to train the model by the command below, a RuntimeError occured, it seems that  GPU of index 0 is always needed, can I train the model without cuda:0?

the command I run:
```
python train.py --gpus 1,2 --cfg $cfg  
# cfg=cfg=config/ade20k-resnet50dilated-ppm_deepsup.yaml 
```
the Error occured:
```
Traceback (most recent call last):
  File "train.py", line 273, in <module>
    main(cfg, gpus)
  File "train.py", line 200, in main
    train(segmentation_module, iterator_train, optimizers, history, epoch+1, cfg)
  File "train.py", line 41, in train
    loss, acc = segmentation_module(batch_data)
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 146, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:1 (device_ids[0]) but found one of them on device: cuda:0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 21, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 276, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/connection.py", line 746, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/anaconda/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

```

**Comment by caidwang** [comment]
If the command goes like
```
python train.py --gpus 0,1 --cfg $cfg
```
or 
```
python train.py --gpus 0,2 --cfg $cfg
```
then no such errors. But peers always occupy the 0 gpu so that my code is hung for long time.

**Comment by hangzhaomit** [comment]
@caidwang it seems to be a bug in our syncBN, implementation, will try to fix that.
At the same time, you might want to do
```CUDA_VISIBLE_DEVICES=1,2 python train.py --gpus 0,1 --cfg $cfg```

**Comment by caidwang** [comment]
> @caidwang it seems to be a bug in our syncBN, implementation, will try to fix that.
> At the same time, you might want to do
> `CUDA_VISIBLE_DEVICES=1,2 python train.py --gpus 0,1 --cfg $cfg`

It works. Thank you.
