### ISSUE TITLE
Unable to train

### ISSUE THREAD

**Issue by solodova** [CSAILVision/semantic-segmentation-pytorch#203]
When I try to run python train.py with the ADEChallenge2016 dataset downloaded, I get a lot of errors:

First I get this:

  File "train.py", line 325, in <module>
    main(args)
  File "train.py", line 200, in main
    train(segmentation_module, iterator_train, optimizers, history, epoch, args)
  File "train.py", line 37, in train
    loss, acc = segmentation_module(batch_data)
  File "/scratch/olga/semantic-segmentation-pytorch/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/olga/SEM_SEG_ZIKUN/cars/code/image2image_models/semantic_seg_colorLabels/models/models.py", line 33, in forward
    (pred, pred_deepsup) = self.decoder(self.encoder(feed_dict['img_data'], return_feature_maps=True))
TypeError: list indices must be integers or slices, not str

I then change feed_dict to feed_dict[0], so the above error is removed, but then this error comes up: 

Traceback (most recent call last):
  File "train.py", line 325, in <module>
    main(args)
  File "train.py", line 200, in main
    train(segmentation_module, iterator_train, optimizers, history, epoch, args)
  File "train.py", line 37, in train
    loss, acc = segmentation_module(batch_data)
  File "/scratch/olga/semantic-segmentation-pytorch/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/olga/SEM_SEG_ZIKUN/cars/code/image2image_models/semantic_seg_colorLabels/models/models.py", line 34, in forward
    (pred, pred_deepsup) = self.decoder(self.encoder(feed_dict['img_data'], return_feature_maps=True))
  File "/scratch/olga/semantic-segmentation-pytorch/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/olga/SEM_SEG_ZIKUN/cars/code/image2image_models/semantic_seg_colorLabels/models/models.py", line 255, in forward
    x = self.relu1(self.bn1(self.conv1(x)))
  File "/scratch/olga/semantic-segmentation-pytorch/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/olga/semantic-segmentation-pytorch/env/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/scratch/olga/semantic-segmentation-pytorch/env/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

Am I doing something wrong and how can I get rid of these errors to run the training script?

**Comment by EricaMoreira** [comment]
Did you find a solution to this? I am having the same issue! Thanks.

**Comment by Ilancia** [comment]
I've been facing exactly errors too. The last one seems related to the fact that model and input don't run on the same device (one on GPU and one on CPU) as suggested [here](https://github.com/sksq96/pytorch-summary/issues/57) and [here](https://discuss.pytorch.org/t/runtimeerror-input-type-torch-cuda-floattensor-and-weight-type-torch-floattensor-should-be-the-same/21782). Moreover, the traceback suggests that we need to locate the input into the GPU, because the model is already there.

Here is the modification I applied just before the computation done for the batch forward, it works for me. 
```python
# from models/models.py ln. 30
def forward(self, feed_dict, *, segSize=None):
	# if the dataset is loaded as a list, this will
	# raise a TypeError while trying to access it as a dictionary.
	if type(feed_dict) is list:
		feed_dict = feed_dict[0]
		# also, convert to torch.cuda.FloatTensor
		if torch.cuda.is_available():
			feed_dict['img_data'] = feed_dict['img_data'].cuda()
			feed_dict['seg_label'] = feed_dict['seg_label'].cuda()
		else:
			raise RunTimeError('Cannot convert torch.Floattensor into torch.cuda.FloatTensor')
```
It is possible that you run in a CUDA out-of-memory-error: this happened to me before upgrading to a more powerful GPU. 

Hope it helps!

**Comment by SiyangXie** [comment]
@Fiordarancio it's RuntimeError not RunTimeError
