### ISSUE TITLE
Training error: num_sample

### ISSUE THREAD

**Issue by shamangary** [CSAILVision/semantic-segmentation-pytorch#204]
I follow the instruction but result in the following error.
Please check on this. Thanks.

```
#Platform
pytorch 1.2.0
distributed branch
single gpu 0

-------------------------------------------
#command
python3 train.py --gpus 0 --cfg config/ade20k-mobilenetv2dilated-c1_deepsup.yaml

-------------------------------------------
#Error message
Launch GPU: 0 for training
Dataset Samples #total: 20210, #process [0]: 0-20210
Traceback (most recent call last):
  File "train.py", line 279, in <module>
    mp.spawn(main_worker, nprocs=num_gpus, args=(cfg, rank2gpu))
  File "/home/shamangary/anaconda3/envs/py3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/shamangary/anaconda3/envs/py3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/shamangary/anaconda3/envs/py3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/shamangary/Desktop/codeDemo/semantic-segmentation-pytorch-distributed/train.py", line 203, in main_worker
    cfg.TRAIN.epoch_iters = len(dataset_train) // cfg.TRAIN.batch_size_per_gpu
  File "/home/shamangary/Desktop/codeDemo/semantic-segmentation-pytorch-distributed/dataset.py", line 197, in __len__
    return self.num_sample
AttributeError: 'TrainDataset' object has no attribute 'num_sample'

```

**Comment by ShihuaiXu** [comment]
have you found the solution? @shamangary

**Comment by shamangary** [comment]
Unfortunately, no.
