### ISSUE TITLE
The thread seems suspended when I deploy my own model on ADE20K datasets

### ISSUE THREAD

**Issue by alanyannick** [CSAILVision/semantic-segmentation-pytorch#71]
Hi,

After running the training scripts, the project just suspended there and had no warning with self-defined encoder rather than ResNet50.  The log has been printed like:
```
-------------------
num_class        150
workers          16
num_gpus         4
batch_size_per_gpu 4
XXXXXXXX
# samples: 20210
1 Epoch = 1000 iters
-------------------
```
While if I change the configuration as following, the program can begin training procedure immediately and print one line log. After that, just stop again.

```
-------------------
num_class        150
workers          16
num_gpus         2
batch_size_per_gpu 2
XXXXXXXX
# samples: 20210
1 Epoch = 1000 iters
 history['train']['acc'].append(acc.data[0])
Epoch: [1][0/1000], Time: 12.53, Data: 1.14, lr_encoder: 0.001000, lr_decoder: 0.001000, Accuracy: 0.25, Loss: 5.052762
-------------------
```

BTW, if I set the batch size large than 4, the following error will happen:
```
-------------------
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
 ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
 ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
 ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
RuntimeError: DataLoader worker (pid 16199) is killed by signal: Bus error.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "lib/utils/data/dataloader.py", line 70, in _worker_manager_loop
    r = in_queue.get()
  File "/root/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/root/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/root/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

-------------------
```
Do you have any ideas?  Looking forward to your response.
Thanks a lot.

**Comment by hangzhaomit** [comment]
It should be a memory issue, please try batch_size_per_gpu=1 first, and let us know if it works.

**Comment by alanyannick** [comment]
It may be the problem of memory issue. 
After changing some parameters of configuration like learning rate and image size, it works.

**Comment by PkuRainBow** [comment]
@alanyannick  Hi, I also meet similar problem but fail to solve it by chaning the image size.

I am using 4 x TITANX wi th batch_size_per_gpu=2.

**Comment by yjykitty** [comment]
same here, @PkuRainBow  have you solved this issue?
