### ISSUE TITLE
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/

### ISSUE THREAD

**Issue by Deeplearning20** [CSAILVision/semantic-segmentation-pytorch#78]
I use this code just to do the test, the implementation of test.py has such a problem. The computer has been restarted. It is useless. My CUDA is 9.0. CUDA is fine on tensorflow.Do you have such a problem? Thank you

z@ss-B250-HD3:/home/dpl/zhaolp/semantic-segmentation-pytorch-master/semantic-segmentation-pytorch-master$ python test.py 
Namespace(arch_decoder='ppm_bilinear_deepsup', arch_encoder='resnet50_dilated8', batch_size=1, fc_dim=2048, gpu_id=0, imgMaxSize=1000, imgSize=[300, 400, 500, 600], model_path='./MODEL_PATH/model_path', num_class=150, num_val=-1, padding_constant=8, result='.', segm_downsampling_rate=8, suffix='_epoch_20.pth', test_img='./TEST_IMG/test_img')
Loading weights for net_encoder
Loading weights for net_decoder
# samples: 1
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCTensorRandom.cu line=25 error=30 : unknown error
Traceback (most recent call last):
  File "test.py", line 173, in <module>
    main(args)
  File "test.py", line 106, in main
    segmentation_module.cuda()
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 249, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 182, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 249, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (30) : unknown error at/pytorch/aten/src/THC/THCTensorRandom.cu 
         :25

**Comment by DARREN0** [comment]
i have the same problem,do you find the method to solve it?

**Comment by Deeplearning20** [comment]
I can change a computer, the problem should be related to the pytorch version.I replaced the python3.6 cuda9.0, formerly python3.5 cuda9.0, hoping to help you
