### ISSUE TITLE
When trying to train getting list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by jackaceuser** [CSAILVision/semantic-segmentation-pytorch#84]
I just cloned the repo, copied the dataset and executed:
"python 3 train.py --num_gpus 1"

It crashes like that:
Traceback (most recent call last):
  File "train.py", line 314, in <module>
    main(args)
  File "train.py", line 200, in main
    train(segmentation_module, iterator_train, optimizers, history, epoch, args)
  File "train.py", line 37, in train
    loss, acc = segmentation_module(batch_data)
  File "/home/shrek/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shrek/projects/semantic-segmentation-pytorch3/models/models.py", line 32, in forward
    (pred, pred_deepsup) = self.decoder(self.encoder(feed_dict['img_data'], return_feature_maps=True))
TypeError: list indices must be integers or slices, not str

When I fix it by adding the line: feed_dict = feed_dict[0] (because it's a list of length 1 of dictionaries)
It crashes with this error:

Traceback (most recent call last):
  File "train.py", line 314, in <module>
    main(args)
  File "train.py", line 200, in main
    train(segmentation_module, iterator_train, optimizers, history, epoch, args)
  File "train.py", line 37, in train
    loss, acc = segmentation_module(batch_data)
  File "/home/shrek/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shrek/projects/semantic-segmentation-pytorch3/models/models.py", line 33, in forward
    (pred, pred_deepsup) = self.decoder(self.encoder(feed_dict['img_data'], return_feature_maps=True))
  File "/home/shrek/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shrek/projects/semantic-segmentation-pytorch3/models/models.py", line 264, in forward
    x = self.relu1(self.bn1(self.conv1(x)))
  File "/home/shrek/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shrek/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'weight'

**Comment by chendeguang** [comment]
您解决了这个问题吗，我现在也遇到了

**Comment by neverstoplearn** [comment]
> 您解决了这个问题吗，我现在也遇到了

I have also meet this error  have you fix it? thanks.

**Comment by Ritian-Li** [comment]
> > 您解决了这个问题吗，我现在也遇到了
> 
> I have also meet this error have you fix it? thanks.


Does it occured in '(pred, pred_deepsup) = self.decoder(self.encoder(feed_dict['img_data'], return_feature_maps=True))' ?
Add [0] before 'img_data' like this "feed_dict[0]['img_data']".
Or you can print the error dict to check it structer

**Comment by shenw000** [comment]
I have the same problem when running the train.py on a Ubuntu 20.04 workstation of 1 GPU. It is solved similar to that in #58 
Replace line 38 `batch_data, src_idx = next(iterator)` of train.py with the following: 

```
batch_data = next(iterator)[0][0]
for k in batch_data.keys():
     batch_data[k] = batch_data[k].cuda()
```
