### ISSUE TITLE
How to test a list of images in a folder?

### ISSUE THREAD

**Issue by happsky** [CSAILVision/semantic-segmentation-pytorch#90]
How to test a list of images in a folder? It seems that the comment `python test.py --test_img ./test_data  --result ./test_results --num_val 20 --model_path ./baseline-resnet50_dilated8-ppm_bilinear_deepsup/` is not working.

Namespace(arch_decoder='ppm_bilinear_deepsup', arch_encoder='resnet50_dilated8', batch_size=1, fc_dim=2048, gpu_id=0, imgMaxSize=1000, imgSize=[300, 400, 500, 600], model_path='./baseline-resnet50_dilated8-ppm_bilinear_deepsup/', num_class=150, num_val=20, padding_constant=8, result='./test_results', segm_downsampling_rate=8, suffix='_epoch_20.pth', test_img='./test_data')
Loading weights for net_encoder
Loading weights for net_decoder
# samples: 1
Traceback (most recent call last):
  File "test.py", line 173, in <module>
    main(args)
  File "test.py", line 109, in main
    test(segmentation_module, loader_val, args)
  File "test.py", line 40, in test
    for i, batch_data in enumerate(loader):
  File "/home/csdept/projects/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 283, in __next__
    return self._process_next_batch(batch)
  File "/home/csdept/projects/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 303, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IsADirectoryError: Traceback (most recent call last):
  File "/home/csdept/projects/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/csdept/projects/semantic-segmentation-pytorch/lib/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/csdept/projects/semantic-segmentation-pytorch/dataset.py", line 263, in __getitem__
    img = imread(image_path, mode='RGB')
  File "/home/csdept/anaconda3/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/csdept/anaconda3/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 164, in imread
    im = Image.open(name)
  File "/home/csdept/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2548, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: './test_data'

**Comment by Tete-Xiao** [comment]
Because the code is for testing a single image. Please read the codes, you should be able to modify it with just a few lines.

**Comment by jeewa985** [comment]
@happsky  did you abel to run the test.py for list of images in folder?
